// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./VeritasFraction.sol";

interface IERC20 {
    function transfer(address recipient, uint256 amount) external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

/**
 * @title VeritasAssetVault
 * @dev Core Vault & Staking Engine for VeritasRWA on BOT Chain Mainnet.
 * Handles fractional asset purchases using native $BOT or $USDT, stakes fractions,
 * and streams real-time yield rewards generated by physical assets & AI Agent rebalancing.
 */
contract VeritasAssetVault {
    address public owner;
    address public usdtTokenAddress; // BOT Chain USDT: 0xaBabc7Ddc03e501d190C676BF3d92ef0e6e87a3C
    address public aiAgentManager;

    uint256 public constant BOT_PER_USDT_RATE = 5; // 1 USDT = 5 BOT (Simulated Oracle Rate)
    uint256 public rewardRatePerSecond = 1e14; // Base yield stream in BOT wei per fraction per second

    struct StakerInfo {
        uint256 stakedFractions;
        uint256 lastClaimTimestamp;
        uint256 unclaimedRewardsBOT;
        uint256 totalRewardsClaimedBOT;
    }

    // Mapping from Asset Token Address => User Address => StakerInfo
    mapping(address => mapping(address => StakerInfo)) public stakers;
    mapping(address => bool) public registeredAssets;

    event AssetPurchased(address indexed buyer, address indexed assetToken, uint256 fractionsMinted, uint256 paidBOT, bool paidInUSDT);
    event FractionsStaked(address indexed user, address indexed assetToken, uint256 amount);
    event FractionsUnstaked(address indexed user, address indexed assetToken, uint256 amount);
    event YieldClaimed(address indexed user, address indexed assetToken, uint256 rewardAmountBOT);
    event RewardRateUpdated(uint256 newRate);

    modifier onlyOwner() {
        require(msg.sender == owner, "VeritasAssetVault: Not owner");
        _;
    }

    modifier onlyAIAgent() {
        require(msg.sender == aiAgentManager || msg.sender == owner, "VeritasAssetVault: Not AI agent manager");
        _;
    }

    constructor(address _usdtAddress) {
        owner = msg.sender;
        usdtTokenAddress = _usdtAddress;
    }

    function setAIAgentManager(address _aiAgent) external onlyOwner {
        aiAgentManager = _aiAgent;
    }

    function registerAsset(address _assetToken) external onlyOwner {
        registeredAssets[_assetToken] = true;
    }

    function setRewardRate(uint256 _newRate) external onlyAIAgent {
        rewardRatePerSecond = _newRate;
        emit RewardRateUpdated(_newRate);
    }

    /**
     * @dev Purchase fractional RWA tokens directly with native BOT coin
     */
    function purchaseFractionsWithBOT(address _assetToken, uint256 _fractionsToBuy, uint256 _pricePerFractionBOT) external payable {
        require(registeredAssets[_assetToken], "VeritasAssetVault: Asset not registered");
        uint256 totalCostBOT = _fractionsToBuy * _pricePerFractionBOT;
        require(msg.value >= totalCostBOT, "VeritasAssetVault: Insufficient BOT value sent");

        // Mint fractional tokens directly to buyer
        VeritasFraction(_assetToken).mint(msg.sender, _fractionsToBuy * 10**18);

        // Auto-stake for immediate yield generation
        _stakeFractions(msg.sender, _assetToken, _fractionsToBuy * 10**18);

        emit AssetPurchased(msg.sender, _assetToken, _fractionsToBuy, totalCostBOT, false);
    }

    /**
     * @dev Purchase fractional RWA tokens using ERC20 USDT
     */
    function purchaseFractionsWithUSDT(address _assetToken, uint256 _fractionsToBuy, uint256 _pricePerFractionUSDT) external {
        require(registeredAssets[_assetToken], "VeritasAssetVault: Asset not registered");
        uint256 totalCostUSDT = _fractionsToBuy * _pricePerFractionUSDT;

        // Transfer USDT from buyer to vault
        bool success = IERC20(usdtTokenAddress).transferFrom(msg.sender, address(this), totalCostUSDT);
        require(success, "VeritasAssetVault: USDT transfer failed");

        // Mint fractional tokens directly to buyer
        VeritasFraction(_assetToken).mint(msg.sender, _fractionsToBuy * 10**18);

        // Auto-stake for immediate yield generation
        _stakeFractions(msg.sender, _assetToken, _fractionsToBuy * 10**18);

        emit AssetPurchased(msg.sender, _assetToken, _fractionsToBuy, totalCostUSDT, true);
    }

    /**
     * @dev Stake existing RWA fraction tokens to earn continuous yield stream
     */
    function stake(address _assetToken, uint256 _amountWei) external {
        require(registeredAssets[_assetToken], "VeritasAssetVault: Asset not registered");
        require(_amountWei > 0, "VeritasAssetVault: Cannot stake 0");

        VeritasFraction(_assetToken).transferFrom(msg.sender, address(this), _amountWei);
        _stakeFractions(msg.sender, _assetToken, _amountWei);
    }

    function _stakeFractions(address _user, address _assetToken, uint256 _amountWei) internal {
        StakerInfo storage info = stakers[_assetToken][_user];
        
        if (info.stakedFractions > 0) {
            uint256 pending = _calculateYield(_user, _assetToken);
            info.unclaimedRewardsBOT += pending;
        }

        info.stakedFractions += _amountWei;
        info.lastClaimTimestamp = block.timestamp;

        emit FractionsStaked(_user, _assetToken, _amountWei);
    }

    /**
     * @dev Claim accumulated BOT yield rewards
     */
    function claimYield(address _assetToken) external {
        StakerInfo storage info = stakers[_assetToken][msg.sender];
        require(info.stakedFractions > 0 || info.unclaimedRewardsBOT > 0, "VeritasAssetVault: No yield to claim");

        uint256 pending = _calculateYield(msg.sender, _assetToken);
        uint256 totalPayout = info.unclaimedRewardsBOT + pending;
        require(totalPayout > 0, "VeritasAssetVault: Zero reward balance");

        info.unclaimedRewardsBOT = 0;
        info.lastClaimTimestamp = block.timestamp;
        info.totalRewardsClaimedBOT += totalPayout;

        // Payout native BOT coin to staker
        if (address(this).balance >= totalPayout) {
            payable(msg.sender).transfer(totalPayout);
        }

        emit YieldClaimed(msg.sender, _assetToken, totalPayout);
    }

    function _calculateYield(address _user, address _assetToken) internal view returns (uint256) {
        StakerInfo memory info = stakers[_assetToken][_user];
        if (info.stakedFractions == 0 || info.lastClaimTimestamp == 0) {
            return 0;
        }

        uint256 duration = block.timestamp - info.lastClaimTimestamp;
        // Yield = duration (seconds) * stakedFractions * rewardRatePerSecond / 1e18
        return (duration * (info.stakedFractions / 10**18) * rewardRatePerSecond);
    }

    function getPendingYield(address _assetToken, address _user) external view returns (uint256) {
        StakerInfo memory info = stakers[_assetToken][_user];
        uint256 pending = _calculateYield(_user, _user);
        return info.unclaimedRewardsBOT + pending;
    }

    receive() external payable {}
}
